# Generated by Django 5.2 on 2025-05-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_rsvpstatus_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpmultidayeventdetails',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpmultidayeventdetails',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpsingledayeventdetails',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpsingledayeventdetails',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
