# Generated by Django 5.2 on 2025-04-18 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_availabilitymatchevent_rsvpbasedevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='myapp.participant'),
        ),
        migrations.AlterField(
            model_name='availabilityintheweek',
            name='selected_day',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
